site_name: ps-MailClient
repo_url: https://github.com/cucumberjim@domain.local/ps-MailClient
theme: readthedocs
edit_uri: edit/master/docs/
pages:
- Home: index.md
- ps-MailClient Basics:
  - What is ps-MailClient: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
